/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sample;

/**
 *
 * @author Mahe
 */
public class RULESANDREG extends javax.swing.JFrame {

    /**
     * Creates new form RULESANDREG
     */
    public RULESANDREG() {
        initComponents();
        String text="GENERAL\n" +
"\n" +
"Facilities of Marena can be utilized only by the students, staffs, staff dependents of Manipal University and TAPMI.\n" +
"Members should carry Identity cards and combo card and show the same at the security counter every day.\n" +
"Members can renew their membership only after the validity period expires.\n" +
"Members who take three and more months membership are eligible for getting TGS key.\n" +
"Pay receipt should be submitted at the marena reception on the same date of payment or the next day.\n" +
"Running and walking shoes (not used outdoor) are allowed only at the gymnasium and jogging track.\n" +
"Members should carry shoes appropriate to the sport and the surface on which they play. Contact the floor supervisor if you have any clarification pertaining to this.\n" +
"Permit shoes to be inspected by the security staff at the entrance every day. Shoes used Outdoor will not be allowed.\n" +
"Please note that membership validity start from the very day or the next day after payment is done. Request to postpone, freeze or carryover the membership will not be entertained.\n" +
"Dependant membership validity will expire on the day of Primary member expiry date.To continue using the facility please renew the Primary membership.\n" +
"Loss of the MARENA access card should be informed immediately and apply for a new one by paying a penalty of INR 100.\n" +
"Transfer of access cards, over writing and tampering in any form will result in permanent cancellation of membership.\n" +
"Membership fee is not refundable.\n" +
"Members have to register their thumb impression every time they visit the facility.\n" +
"Please take care of the property at MARENA. Any kind of loss or damage to the floor or any other property will attract penalty.\n" +
"Members must bring their own sports equipment.\n" +
"GYM­­­­­­­­­­\n" +
"\n" +
"Members are instructed to wear proper sports gear during work out. Jeans, formal wear, fancy shorts will not to be allowed. Please bring your own hand towel and bath towel.\n" +
"Please don’t keep your id card, locker key or any kind of belongings at the gym reception counter\n" +
"Members are instructed to keep the weights (dumbells, barbells, and weight plates) back in their respective places after use. Offenders will be prompted by the trainers to replace the weights. Membership will be cancelled for repeated offenders. Please comply.\n" +
"Weight plates either have in the rack or in the barbell, don’t leave it on the floor or trumpet.\n" +
"Do not use cardio equipments for more than 20 minutes during peak hours.\n" +
"STEAM SOUNA/ LOCKER\n" +
"\n" +
"Do not use steam and sauna facility more than once in a week.\n" +
"Kindly return the locker key before you leave the locker room daily. Members will be fined INR 1000/- on loss of locker key or failure to return to counter.\n" +
"SQUASH/BADMINTON/BASKETBAL/TABLE TENNIS\n" +
"\n" +
"Members are requested not to use badminton, squash, basketball, and table tennis courts for more than 30 minutes during peak hours.\n" +
"You are expected to wear non-marking gum rubber sole shoe for badminton, squash and table tennis.\n" +
"You are expected to wear non-marking carbon rubber or gum rubber soles shoe for Basketball.\n" +
"TENNIS\n" +
"\n" +
"Appropriate tennis shoes are mandatory to use the tennis courts.\n" +
"FUTSAL\n" +
"\n" +
"Studded shoes are not allowed at futsal court.\n" +
"CRICKET\n" +
"\n" +
"Members are requested to use the bowling machine. The position of the bowling Machine should not be shifted at any cost. Manual bowling is strictly prohibited.";
        this.jTextArea1.setText(text);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 784, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RULESANDREG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RULESANDREG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RULESANDREG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RULESANDREG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RULESANDREG().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
